---
- name: Recursively find /var/lib/pgsql/production_dumps
  hosts: dbserver
  become: true
  gather_facts: false

  tasks:
  - name: find *.gz files
    ansible.builtin.find:
      paths: "{{dump_path}}"
      patterns: "{{dump_pattern}}"
      recurse: true
    register: output_find

  - name: print file *.gz 
    ansible.builtin.debug:
      var: output_find
