---
- name: Recursively find /var/lib/pgsql/production_dumps/
  hosts: dbserver
  tasks:
   - name: find dumps
     ansible.builtin.find:
      path: /var/lib/pgsql/production_dumps/
      patterns: "*.gz"
